--- 
document: 
  description: "Linee guida sull'accessibilità degli strumenti informatici"
  name: "Linee guida sull'accessibilità degli strumenti informatici"
  tags: 
    - linee guida
    - accessibilità
    - design